spring.datasource.url=jdbc:mysql://localhost:3306/smart_wallet_app?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=kashkaval83!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Notifications
notification-svc.failure-message.clear-history=Notification service is temporary down! Please try again later!
notification-svc.failure-message.retry-notifications=Notification service is out of order! Please try again later!
